version: "3.7"
services:
  app:
    build:
      args:
        user: www
        uid: ${UID}
      context: ./
      dockerfile: Dockerfile
    image: laravel-image
    container_name: gb-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./Docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      COMPOSER_MEMORY_LIMIT: 2G
      XDEBUG_CONFIG: client_host=${XDEBUG_REMOTE_HOST} client_port=${XDEBUG_STORM_PORT} remote_enable=1
      PHP_IDE_CONFIG: serverName=${XDEBUG_STORM_SERVER_NAME}


  db:
    image: mysql:5.7
    container_name: gb-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./Docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./Docker/mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/

  nginx:
    image: nginx:alpine
    container_name: gb-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./Docker/nginx/conf.d/:/etc/nginx/conf.d/
