name: Deploy Deployment
on: 
  push:
    branches: [main, completed]
env:
  FIRST_NAME: Test    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          echo $FIRST_NAME
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.HOST_SSH_KEY }}
          username: ${{ secrets.HOST_USERNAME }}
          #port: $HOST_PORT
          script: |
            echo $FIRST_NAME
            cd /var/www/html/
            git checkout -f 
            git pull origin master
      #- name: Checkout the repo
      #  uses: actions/checkout@v3
      #  with:
      #    path: '/home/expertland/'
#          pass: ${{ secrets.PASS }}
#          args: "-tt -vvv"
#        env:
#          HOST_PORT: ${{ secrets.HOST_PORT }}
#        with:
#          host: ${{secrets.HOST}}
#          key: ${{secrets.HOST_SSH_KEY}}
#          username: ${{secrets.HOST_USERNAME}}
#          port: $HOST_PORT
#          script: |  
#            ls
#            cd /home/ubuntu/expertland/
#            git clone git@github.com:oisachenko/openmct-tutorial.git
#            echo 'Deployment successful'
