name: Deploy Deployment
on: 
  push:
    branches: [main, completed]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: appleboy/ssh-action@master
        env:
          HOST_PORT: ${{ secrets.HOST_PORT }}
        with:
          host: ${{secrets.HOST}}
          key: ${{secrets.HOST_SSH_KEY}}
          username: ${{secrets.HOST_USERNAME}}
          port: $HOST_PORT
          script: |  
            ls
            cd /home/ubuntu/expertland/
            git clone git@github.com:oisachenko/openmct-tutorial.git
            echo 'Deployment successful'
