name: Deploy Deployment
on: 
  push:
    branches: [main, completed]
env:
  FIRST_NAME: Test    
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /tmp
            ls -a
            echo "env_var:$FIRST_NAME"
            exit 1
          host: ${{secrets.HOST}}
          port: ${{ secrets.HOST_PORT }}
          user: ${{secrets.HOST_USERNAME}}
          key: ${{secrets.HOST_SSH_KEY}}
#          pass: ${{ secrets.PASS }}
#          args: "-tt -vvv"
#        env:
#          HOST_PORT: ${{ secrets.HOST_PORT }}
#        with:
#          host: ${{secrets.HOST}}
#          key: ${{secrets.HOST_SSH_KEY}}
#          username: ${{secrets.HOST_USERNAME}}
#          port: $HOST_PORT
#          script: |  
#            ls
#            cd /home/ubuntu/expertland/
#            git clone git@github.com:oisachenko/openmct-tutorial.git
#            echo 'Deployment successful'
