name: Deploy Deployment
on:
  push:
    branches: [dev]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      #- name: Checkout.
      #  uses: actions/checkout@v2
      - name: Checkout and Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.HOST_SSH_KEY }}
          username: ${{ secrets.HOST_USERNAME }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            cd /home/ubuntu/expertland
            docker-compose down
            git pull origin
            docker-compose up -d
            echo 'pausing: waiting for mysql to come available'
            chmod a+x Docker/wait-for-mysql.sh
            ./Docker/wait-for-mysql.sh
            echo 'un-pausing: mysql is now available'
      - name: In docker container run
        uses: appleboy/ssh-action@master
        #if: ${{ false }}
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.HOST_SSH_KEY }}
          username: ${{ secrets.HOST_USERNAME }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            cd /home/ubuntu/expertland
            docker-compose exec -T app composer install
            docker-compose exec -T app php artisan key:generate
            docker-compose exec -T app php artisan config:clear
            docker-compose exec -T app php artisan cache:clear
            docker-compose exec -T app php artisan migrate --seed
            docker-compose exec -T app npm install
            docker-compose exec -T app npm run build
