name: Deploy Deployment
on: 
  push:
    branches: [main, completed]
env:
  FIRST_NAME: Test    
jobs:
  build: 
    runs-on: self-hosted
    steps:
      - name: Change work folder
        run: |
          cd /home/ubuntu/expertland/
      - name: Checkout manual
        run: |  
          ls
          cd /home/ubuntu/expertland/
          git clone git@github.com:oisachenko/openmct-tutorial.git
      #- name: Checkout the repo
      #  uses: actions/checkout@v3
      #  with:
      #    path: '/home/expertland/'
#          pass: ${{ secrets.PASS }}
#          args: "-tt -vvv"
#        env:
#          HOST_PORT: ${{ secrets.HOST_PORT }}
#        with:
#          host: ${{secrets.HOST}}
#          key: ${{secrets.HOST_SSH_KEY}}
#          username: ${{secrets.HOST_USERNAME}}
#          port: $HOST_PORT
#          script: |  
#            ls
#            cd /home/ubuntu/expertland/
#            git clone git@github.com:oisachenko/openmct-tutorial.git
#            echo 'Deployment successful'
