name: Stage Deployment
on: 
  push:
    tags:
    - stage-*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: Build and push Docker 
        uses: docker/build-push-action@v1
        with: 
          username: ${{secrets.DOCKERHUB_username}}
          password: ${{secrets.DOCKERHUB_password}}
          repository: oiscore/gitactions
          tag_with_ref: true
          tag_with_sha: true
  deploy:
    needs: build

    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: Get tag name
        uses: olegtarasov/get-tag@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          tocken: ${{secrets.DIGITALOCEAN_ACCESS_TOCKEN}}
      - name: Provision Droplet and deploy container
        run: doctl compute droplet create "$GIT_TAG_NAME" --image docker-18-04 --size s-1vcpu-1gb --region nyc1 --user-data-file deploy.sh --wait



